### ISSUE TITLE
[1.18.2 - FML] Unable to start Atlas Combat

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#10]
I think this might be a outdated forge version issue? not sure

**log:**
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10885342/latest.log)

**(line 202):**
```
[12:52:05] [main/INFO]: No dependencies to load found. Skipping!
[12:52:05] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'atlascombat', Expected range: '[44,)', Actual version: '40.2.1'
[12:52:12] [main/INFO]: Compatibility level set to JAVA_17
```

**Comment by Cixon** [comment]
**Debug:**
[debug.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10885390/debug.log)

**Comment by No1129** [comment]
there is no forge 44. on 1.18.2
so the issue may be that the mod is too updated

**Comment by Cixon** [comment]
previous logs are irrelevant. attempted to use build from 3/3/2023 12:05pm **_(210.73 KB)_**
sadly the client couldn't start, here's the log for the most recent build:
https://pastebin.com/KjNbK440

**Comment by zOnlyKroks** [comment]
Quick question: Does this error happen with only Atlas Combat installed, or does it only crash when certain mods are installed?

**Comment by Cixon** [comment]
> Quick question: Does this error happen with only Atlas Combat installed, or does it only crash when certain mods are installed?

This occurs when only atlas is installed. I saw 20 minutes ago you guys published a new build but sadly my client wont start.

**Additional Context:**
FML 1.18
Forge: 40.2.1

**New latest.log:**
https://pastebin.com/uawEDXJU

**Comment by zOnlyKroks** [comment]
That build only fixes anither Error a few Users had, beeing that i shaded Mixin Extras wrong

**Comment by Cixon** [comment]
thanks for letting me know, I'll wait for this fix

> **New latest.log:** https://pastebin.com/uawEDXJU

**Comment by Alexandra-Myers** [comment]
> there is no forge 44. on 1.18.2 so the issue may be that the mod is too updated

this problem was caused by a small issue in my mods.toml file, sorry
