### ISSUE TITLE
[Mod-conflict] Shield Expansion cannot currently coexist with Atlas

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#11]
It appears the client will not start if both mods are installed, I assume this has something to do with both mixins butting heads.
I'll let y'all check out the debug and logs in question to terminate the best course of action!

### Latest Log (not that relevant but sent anyways) :
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10920661/latest.log)

Debug log:
[debug.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10920668/debug.log)

**Comment by Cixon** [comment]
**Mod in question:**

https://www.curseforge.com/minecraft/mc-mods/shield-expansion

**Comment by Alexandra-Myers** [comment]
Unfortunately the crash does not seem to be caused by an incompatibility, but rather by an issue on shield expansion's part. If you would like to know what you should say to them in a issue report, I would recommend something along the lines of "Mixin config specifies Java version 8 but 1.18 uses version 17" as the mixin config is built for 1.16 rather than 1.18+. There should be zero incompatibilities once this is fixed.

**Comment by Cixon** [comment]
> Unfortunately the crash does not seem to be caused by an incompatibility, but rather by an issue on shield expansion's part. If you would like to know what you should say to them in a issue report, I would recommend something along the lines of "Mixin config specifies Java version 8 but 1.18 uses version 17" as the mixin config is built for 1.16 rather than 1.18+. There should be zero incompatibilities once this is fixed.

I'll mention this ticket over to their github, thanks

**Comment by Cixon** [comment]
Error persists even with latest Shield-Expansion [fix via recent 1.1.6 update](https://www.curseforge.com/minecraft/mc-mods/shield-expansion/files/4461131).

Debug:
[debug.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/11084407/debug.log)

**Comment by Alexandra-Myers** [comment]
I still do not understand what is wrong here

**Comment by Alexandra-Myers** [comment]
I found it. the crash is different. this one I don't think any code improvements will solve.

**Comment by Alexandra-Myers** [comment]
but I found a fix. this was one of Finn's nasty overwrites...

**Comment by Cixon** [comment]
> but I found a fix. this was one of Finn's nasty overwrites...

Uh oh, lol
