### ISSUE TITLE
Crash On Startup - Fabric 1.19.2 - 1.1.3

### ISSUE THREAD

**Issue by Spenz0r** [Alexandra-Myers/Atlas-Combat#14]
I have owo-lib installed and trying different versions of it doesn't do anything.
Whenever I try to start the game with the mod I get an exit code 1.

[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10949225/latest.log)

Here is the latest.log file.

**Comment by zOnlyKroks** [comment]
Can you Post the complete modlist please?

**Comment by Spenz0r** [comment]
Sure thing

- Alternate Current
- Ambient Environment
- Amplified Nether
- Animatica
- Architectury API
- Armor Statues
- Auditory
- Auudio
- BCLib
- BedrockWaters
- Bedspreads
- Beenfo
- Better Mount HUD
- Better Recipe Book
- Better Statistics Screen
- Better Tridents
- BetterEnd
- BetterF3
- BetterNether
- Boat Item View
- Bundles Unlocked
- Carpeted Stairs
- Carry On
- Chat Heads
- Cherished Worlds
- Chisels & Bits
- CleanCut
- Cloth Config API
- Clumps
- Connectivity
- Continuity
- Controlling
- Create Deco Fabric
- Create Fabric
- Create: Extended Flywheels
- Creeper Overhaul
- CTM Refabricated
- Dark Loading Screen
- Debugify
- Deeper and Darker
- Disable Insecure Chat Toast
- Easy Anvils
- Easy Magic
- Easy Shulker Boxes
- Eating Animation
- Effective
- Enhanced Block Entities
- Entity Collision FPS Fix
- Entity Culling Fabric
- Entity Textures Features Fabric
- Essential
- Fabric API
- Fabric Language Kotlin
- FancyMenu Fabric
- Fast Furnace Fabric
- Fastload
- FerriteCore
- Forge Config API Port
- Friends&Foes
- Galosphere
- Geckolib
- I Know What I'm Doing
- Iceberg
- Indium
- Iris Shaders
- Item Model Fix
- Joy of Painting
- Jumpy Boats
- Konkrete
- Krypton
- LambDynamicLights
- LazyDFU
- Legendary Tooltips
- Lithium
- Map Atlases Fabric
- MemoryLeakFix
- Mod Menu
- Model Gap Fix
- Moonlight Lib
- More Banner Features
- MoreCulling
- Mouse Tweaks
- Mouse Wheelie
- Music Maker
- Music Triggers
- Name Pain
- No Chat Reports
- Not Enough Animations
- Nullscape
- Nyf's Spiders
- owo lib
- Paradise Lost
- Ping Wheel
- Prism
- Puzzles Lib
- Reese's Sodium Options
- Satin API
- ShulkerBoxTooltip
- Simple Voice Chat
- Skin Layers 3D
- Skin Swapper
- Sodium
- Sound Physics Remastered
- Spark
- Starlight
- Storage Labels
- Structory
- Supplementaries
- TalkBubbles
- Terralith
- The Impossible Library
- True Darkness
- Tumbleweed
- Visual Overhaul
- Visual Workbench
- Visuality
- Wilder Wild
- YetAnotherConfigLib
- YUNG's API
- YUNG'S Better Desert Temples
- YUNG'S Better Mineshafts
- YUNG'S Better Ocean Monuments
- YUNG'S Better Strongholds

**Comment by Shywizz** [comment]
This crash seems to happen whatever i do, i have tried loading the bare minimum with only fabric api , owo and this mod but its still crash, wish i could play on 1.19.2, please fix !

**Comment by Alexandra-Myers** [comment]
fixed in 1.1.4
