### ISSUE TITLE
Incompatibility with collective.

### ISSUE THREAD

**Issue by xelotex** [Alexandra-Myers/Atlas-Combat#16]
[crash-2023-02-26_17.02.43-fml.txt](https://github.com/Alexandra-Myers/Atlas-Combat/files/10973610/crash-2023-02-26_17.02.43-fml.txt)

Game version: 1.19.2

Mod version: Atlas combat 1.1.3, Collective 6.45

Mod loader: Fabric.

**Comment by Alexandra-Myers** [comment]
first issue: you are loading Forge and using Fabric mods. Second issue: the 1.19.2 version is broken. Third issue: the collective incompat is already known

**Comment by Alexandra-Myers** [comment]
the collective issue has been patched
