### ISSUE TITLE
[StartUp-Crash] 1.18x Forge

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#19]
Crash Report:
[crash-2023-05-15_18.20.46-client.txt](https://github.com/Alexandra-Myers/Atlas-Combat/files/11482579/crash-2023-05-15_18.20.46-client.txt)

Log:
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/11482577/latest.log)

**Comment by Alexandra-Myers** [comment]
do you know if this is caused by Atlas Combat?

**Comment by Cixon** [comment]
> do you know if this is caused by Atlas Combat?

yes. if you try my mod pack that’s available then add Atlas, it crashes on startup.

link: https://legacy.curseforge.com/minecraft/modpacks/legacy-forge

**Comment by Alexandra-Myers** [comment]
> > do you know if this is caused by Atlas Combat?
> 
> yes. if you try my mod pack that’s available then add Atlas, it crashes on startup.
> 
> link: https://legacy.curseforge.com/minecraft/modpacks/legacy-forge

then this is an incompatibility issue. have you tried the bare minimum(Atlas Combat only)

**Comment by Cixon** [comment]
the mod works fine alone, the mixins break a good quarter of mods I use which are mods that are popular within the CF community.

**Comment by Cixon** [comment]
I appreciate your dedication, thank you! 😄

**Comment by Cixon** [comment]
fixed in v1.1.5
