### ISSUE TITLE
[FR] Config option to disable -Holding left click attacks 1 tick slower from optimal fast hit timing

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#20]
I think the holding left click feature is wonderful for those in need of accessibility but unfortunately without a option to disable this, it hinders modpack creators as those who remove cool-downs for specific weapons, experience dips in some TPS and also skipping in some i-frames.

If there was a way to disable this in the config for good, it will be wonderful for those who require very specific combat values in their pack and not only this, it will be a balanced experience for online pvp for servers.

**Comment by Alexandra-Myers** [comment]
implemented in 1.1.6

**Comment by Cixon** [comment]
Hey I appreciate this!
