### ISSUE TITLE
[mod-incompat] [1.18-1.19] Add config for custom speed/dmg values

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#21]
### Context:
Hello, I've done some extensive testing with Atlas v[1.1.5](https://legacy.curseforge.com/minecraft/mc-mods/atlas-combat/files/4552632) alongside the latest version of Property Modifier and I've noticed that there were some nasty issues that were apparent upon enabling the config option "attackSpeed". Firstly, the equip logic for tools and weapons were broken. The player wouldn't raise them as if they were too heavy for the player. I knew immediately that this was a incompatibility with two mods attempting to modify the speed values.

### Solution:
Disable your attack speed values in the event the user has PM installed and only apply your values to equipment that do not have modifications from PM.

Mod Link:
https://www.curseforge.com/minecraft/mc-mods/property-modifier

Property Modifier Config:
_(convert to .toml, NOT .txt)_
[propertymodifier-common.txt](https://github.com/Alexandra-Myers/Atlas-Combat/files/11571153/propertymodifier-common.txt)

**Comment by Cixon** [comment]
I think there could be a way to fix this issue universally for other mods/datapacks that change speed values and damage values but I'm not a coder...I just like to test things.

**Comment by Cixon** [comment]
Bug also occurs with SpammyCombat.

**Mod:** https://www.curseforge.com/minecraft/mc-mods/spammycombat

**Comment by Alexandra-Myers** [comment]
"solution" this will in fact break the entire mod, so no.

**Comment by Alexandra-Myers** [comment]
no reason to modify Attack Speed otherwise, unless you want to modify specific tools stats, but for your case, I don't think you do.

**Comment by Alexandra-Myers** [comment]
I may reopen this if I think of something, but consider this a "won't fix" for now

**Comment by Cixon** [comment]
Having speed modifications for my Legacy modpack is essential hence property modifier. The goal is to have no cool-down for swords and only cool-downs for stronger weapons such as Axes and other things. I know I won’t be the only one who removes cool-downs or changes damage/speed values for weapons but I think if the mod’s structure is so sensitivity that it’s impossible to cater to outside modifications such as those values, why not include it as a configuration similar to Property modifier?

Allowing users to choose to make specific speed values and damage values rather than only having to pick between vanilla and atlas’s default would ensure players to stay and keep Atlas installed because it is a little discouraging and I’d like to see some improvement on this, if possible.

I don’t want to stress y‘all because this is a wonderful mod but I’m just putting my two cents here, it is a passion project after all and CF doesn’t really pay much so I know it’s not really something that is within high interest but these are my opinions.

**Comment by Cixon** [comment]
not to mention, it would eliminate a mod or two from my modpack which may or may not improvement performance. I think I’ll only use property modifier to change armor durability values only or something 👍

**Comment by Alexandra-Myers** [comment]
dmg has been changed such that the only rule is that it cannot be negative in 1.1.6, currently working on speed, if speed is greater than 20 I will make it such that the weapon gets speed disabled

**Comment by Alexandra-Myers** [comment]
completed for 1.1.6
