### ISSUE TITLE
[mod-incompat] [start-up phase] Aerial Hell mod

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#23]
### Context:
There seems to be some discrepancy with Aerial Hell. This mod has been out for a while but is slightly new to the 1.18 FML space so I wouldn't be surprised if this error falls on Aerial Hell's fault. I can reach out to original creator as I'm actually one of his artists for the mod but figured I'd open this ticket as I'm slightly incompetent with understanding this error 😅

**Crash:**
[crash-2023-05-27_08.47.24-fml.txt](https://github.com/Alexandra-Myers/Atlas-Combat/files/11582053/crash-2023-05-27_08.47.24-fml.txt)

**Latest.log (line 171):**
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/11582057/latest.log)

![Screenshot (334)](https://github.com/Alexandra-Myers/Atlas-Combat/assets/69068153/6b314471-6c75-40ce-8b59-a005f1ce873d)

**Comment by Cixon** [comment]
**mod:** https://legacy.curseforge.com/minecraft/mc-mods/aerial-hell

**Comment by Alexandra-Myers** [comment]
wait, why on earth is AerialHellPickaxeItem building it's own attribute modifiers? this is completely unnecessary and has been for, as far as I am aware, the entire history of Minecraft modding. I don't think you should be doing that. If you want to have those extra modifiers, I would instead suggest using `this.defaultModifiers.put(Attributes.MOVEMENT_SPEED, new AttributeModifier(BASE_MOVEMENT_SPEED_UUID, "Weapon modifier", (double)movementSpeedIn, AttributeModifier.Operation.MULTIPLY_TOTAL));` for adding new attribute modifiers to the item. this.defaultModifiers will probably be private, so use an access transformer to gain access and get rid of the override for getAttributeModifiers

**Comment by Alexandra-Myers** [comment]
that way you can call it in the constructor without causing problems.

**Comment by nicochart** [comment]
This problem will be fixed in the next release (the fix is in todays commits)
Thank you for your advices Alexandra-Myers
