### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by xelotex** [Alexandra-Myers/Atlas-Combat#25]
version 1.1.6 causes a crash on startup.
i'm using the version 1.19.2 with forge.

**Comment by Alexandra-Myers** [comment]
more information????

**Comment by xelotex** [comment]
idk, what do you need to know? i just downloaded version 1.1.6 for forge 1.19.2, installed on the game, start the game, and it crashed. 
It doesn't crash for you? Also the shield is not working on the fabric version.

**Comment by Alexandra-Myers** [comment]
I don't know?????? was the shield working on 1.1.5 by any chance? and also do you have any info on the crash?

**Comment by xelotex** [comment]
no, there's no crash report, if you want i can make a video

**Comment by Alexandra-Myers** [comment]
you can also just look at latest.log????

**Comment by xelotex** [comment]
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/11586966/latest.log)
Alright

**Comment by Alexandra-Myers** [comment]
I meant for Forge crash. But I already looked at it

**Comment by xelotex** [comment]
https://www.youtube.com/watch?v=IPL-EEDTAXQ

**Comment by Alexandra-Myers** [comment]
do you know if this happens on 1.1.5?

**Comment by xelotex** [comment]
let me check

**Comment by xelotex** [comment]
> do you know if this happens on 1.1.5?

yep, it does happen

**Comment by Alexandra-Myers** [comment]
sorry about this, but I am going to need some time to find solutions, and the actual problems

**Comment by xelotex** [comment]
fine, don't worry

**Comment by Alexandra-Myers** [comment]
Fixed shield bug, currently nothing has been done on FML, but in 1.1.7 both of these will be fixed
