### ISSUE TITLE
[1.18.2 FML] [1.1.6] Atlas holds client hostage

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#26]
### Context:
I updated this mod with my modpack and noticed the launcher was no longer prompting the start-up phase. I then disabled Atlas and got the start-up phase as per usual. I then tried to remove my config file and re-enabled Atlas but this did not fix the issue.

### Debug (line 3,896):
[debug.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/11587760/debug.log)

**Comment by Alexandra-Myers** [comment]
yeah, there is a forge problem rn

**Comment by Cixon** [comment]
gotcha. appreciate the reply, wish to see a fix soon

**Comment by Cixon** [comment]
Heya Atlas team! Thanks for the tester role on CF. I really appreciate that recognition.
Is there still a fix underway for this issue still? I hate to have this mod disabled as it's one of the main assets in my modpack. It essentially erases all other combat related mods because it's very versatile and customizable unlike other mods out there.
