### ISSUE TITLE
[1.18.2 - 1.19.2] Attack speed discrepancy with items that have cool-downs.

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#27]
**Disclaimer:** Tested on v1.1.5 of 1.18.2 because v1.1.6 is broken due to #25 & #26.

Video Summary of Bug:
https://streamable.com/oljd0w

Mod inuse:
https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

**Comment by Alexandra-Myers** [comment]
this was fixed in 1.1.6
