### ISSUE TITLE
[1.18.2 FML] Ice and Fire's Phantasmal Blade doesn't shoot ghost projectile.

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#28]
Bug listed in the title. Tested on v.1.1.5 due to #26 & #25

![image](https://github.com/Alexandra-Myers/Atlas-Combat/assets/69068153/888d5837-8361-4f91-b023-c74eb5498e5c)

**Comment by Cixon** [comment]
image above is a demonstration of what should occur when player attacks.

**Comment by Alexandra-Myers** [comment]
it works in 1.1.7
