### ISSUE TITLE
[Universal Bug] Raised not compatible due to hotbar mixins.

### ISSUE THREAD

**Issue by Cixon** [Alexandra-Myers/Atlas-Combat#29]
Creator of Raised said it best so here's a comment on that:
https://github.com/yurisuika/Raised/issues/39#issuecomment-1585844691

Universal because I'm pretty sure this issue is present in all Atlas versions.

**Comment by Alexandra-Myers** [comment]
Fixed in 1.1.7 (probably)

**Comment by Cixon** [comment]
for 1.18.2 fml as well?

**Comment by Alexandra-Myers** [comment]
of course it is, just 1.18.2 FML doesn't have 1.1.7 yet
