### ISSUE TITLE
are you planning to update this mod to the 1.20.1?

### ISSUE THREAD

**Issue by anonimato12345** [Alexandra-Myers/Atlas-Combat#30]
how much time is going to take? im so excited!!!!! .

**Comment by Alexandra-Myers** [comment]
yes, it will happen soon after we are done with 1.1.7

**Comment by Alexandra-Myers** [comment]
> how much time is going to take? im so excited!!!!! .

it will happen after all of the other versions are covered

**Comment by anonimato12345** [comment]
I admire you and your programming skills
