### ISSUE TITLE
[Enhancement] Be able to join servers without the mod, and not use it.

### ISSUE THREAD

**Issue by slushie0** [Alexandra-Myers/Atlas-Combat#7]
When I try to join a vanilla server, It throws an error saying the server doesn't have the mod. If I want to join it, I have to close Minecraft, remove the file from the mods folder, and open it back up. It would be nice if the mod simply only applied on compatible servers.

**Comment by Alexandra-Myers** [comment]
unfortunately doing such would be nigh impossible and also make the mod run worse.
