### ISSUE TITLE
incompat with Origins

### ISSUE THREAD

**Issue by Lolothepro** [Alexandra-Myers/Atlas-Combat#9]
[crash-2023-02-24_12.37.06.9088-quilt_loader.txt](https://github.com/Alexandra-Myers/Atlas-Combat/files/10823664/crash-2023-02-24_12.37.06.9088-quilt_loader.txt)
[latest.log](https://github.com/Alexandra-Myers/Atlas-Combat/files/10823665/latest.log)

**Comment by Alexandra-Myers** [comment]
fixed I think
